# Generated by Django 4.2.3 on 2023-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0004_alter_assignmentstudent_grade_alter_enrollment_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
