# Generated by Django 4.2.3 on 2023-08-19 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0005_alter_questionattempt_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionstudent',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
