# Generated by Django 4.2.3 on 2023-08-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0006_questionattempt_timestamp_questionstudent_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempt',
            old_name='is_successful',
            new_name='success',
        ),
    ]
