# Generated by Django 4.2.3 on 2023-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0022_variable_remove_hint_url_alter_question_answer_type_and_more'),
        ('deimos', '0007_rename_is_successful_questionattempt_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstudent',
            name='instances_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionstudent',
            name='var_instances',
            field=models.ManyToManyField(related_name='question_students', to='phobos.variableinstance'),
        ),
    ]
