# Generated by Django 4.2.3 on 2023-09-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0008_questionstudent_instances_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentstudent',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
