# Generated by Django 4.2.3 on 2023-09-29 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0009_assignmentstudent_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='question',
        ),
        migrations.RemoveField(
            model_name='note',
            name='student',
        ),
        migrations.AddField(
            model_name='note',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='question_student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='deimos.questionstudent'),
            preserve_default=False,
        ),
    ]
