# Generated by Django 4.2.3 on 2023-10-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0010_questionmodifiedscore'),
        ('deimos', '0010_remove_note_question_remove_note_student_and_more'),
    ]

    operations = [
    ]
