# Generated by Django 4.2.3 on 2023-10-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0013_alter_assignmentstudent_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_note', to='deimos.note')),
            ],
        ),
    ]
