# Generated by Django 4.2.3 on 2023-10-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0014_notetemporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='submitted_answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
