# Generated by Django 4.2.3 on 2023-10-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0015_questionattempt_submitted_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='submitted_units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='units_success',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
