# Generated by Django 4.2.3 on 2023-10-17 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0016_questionattempt_submitted_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstudent',
            name='num_units_attempts',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
