# Generated by Django 4.2.3 on 2023-11-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0017_questionstudent_num_units_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='submitted_answer',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.CreateModel(
            name='QASuccessPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairs', models.CharField(max_length=2000)),
                ('question_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='success_pairs', to='deimos.questionattempt')),
            ],
        ),
    ]
