# Generated by Django 4.2.4 on 2023-11-17 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0047_remove_matchinganswer_secret_key'),
        ('deimos', '0018_alter_questionattempt_submitted_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_practice_test', to='phobos.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_practice_test', to='phobos.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_practice_test', to='deimos.student')),
            ],
        ),
    ]
