# Generated by Django 4.2.3 on 2023-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0018_alter_questionattempt_submitted_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notetemporary',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
