# Generated by Django 4.2.4 on 2023-11-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0047_remove_matchinganswer_secret_key'),
        ('deimos', '0019_practicetestassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicetestassignment',
            name='assignment',
        ),
        migrations.AddField(
            model_name='practicetestassignment',
            name='assignment',
            field=models.ManyToManyField(blank=True, related_name='practice_test_assignments', to='phobos.assignment'),
        ),
    ]
