# Generated by Django 4.2.3 on 2023-11-10 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0019_note_title_notetemporary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstudent',
            name='num_units_attempts',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
