# Generated by Django 4.2.3 on 2023-11-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0020_alter_questionstudent_num_units_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstudent',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
