# Generated by Django 4.2.3 on 2023-11-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0021_questionstudent_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentstudent',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
