# Generated by Django 4.2.4 on 2023-11-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0020_remove_practicetestassignment_assignment_and_more'),
        ('deimos', '0022_assignmentstudent_is_complete'),
    ]

    operations = [
    ]
