# Generated by Django 4.2.3 on 2023-11-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0049_remove_question_category_unit_questioncategory'),
        ('deimos', '0022_assignmentstudent_is_complete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentstudent',
            unique_together={('student', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='questionstudent',
            unique_together={('student', 'question')},
        ),
    ]
