# Generated by Django 4.2.3 on 2023-12-28 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0023_alter_assignmentstudent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstudent',
            name='grade',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
