# Generated by Django 4.2.3 on 2023-12-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0052_variableinstance2'),
        ('deimos', '0024_questionstudent_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstudent',
            name='var_instances2',
            field=models.ManyToManyField(related_name='question_students', to='phobos.variableinstance2'),
        ),
    ]
