# Generated by Django 4.2.3 on 2023-12-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0025_questionstudent_var_instances2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstudent',
            name='var_instances2',
        ),
    ]
