# Generated by Django 4.2.2 on 2023-07-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0002_alter_course_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='No description', max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses', to='phobos.professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('COMPUTER_SCIENCE', 'Computer Science'), ('MATHS', 'Maths'), ('PHYSICS', 'Physics')], default='PHYSICS', max_length=100),
        ),
    ]
