# Generated by Django 4.2.2 on 2023-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0003_course_description_alter_course_professors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phobos/images/course_images/'),
        ),
    ]
