# Generated by Django 4.2.1 on 2023-07-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0005_topic_rename_unit_question_sub_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionanswer',
            name='is_answer',
        ),
        migrations.RemoveField(
            model_name='vectoranswer',
            name='is_answer',
        ),
    ]
