# Generated by Django 4.2.1 on 2023-07-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0006_remove_expressionanswer_is_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phobos/images/course_covers'),
        ),
    ]
