# Generated by Django 4.2.3 on 2023-08-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0010_alter_subtopic_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpressionAnswer',
            new_name='McqExpressionAnswer',
        ),
        migrations.RemoveField(
            model_name='floatanswer',
            name='is_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
