# Generated by Django 4.2.3 on 2023-08-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0012_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
