# Generated by Django 4.2.3 on 2023-08-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0016_textanswer_mcqtextanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phobos.subtopic'),
        ),
    ]
