# Generated by Django 4.2.3 on 2023-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0017_alter_question_sub_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('HOMEWORK', 'Homework'), ('PRACTICE_TEST', 'Practice Test')], default='HOMEWORK', max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STRUCTURAL_EXPRESSION', 'Structural Expression'), ('STRUCTURAL_FLOAT', 'Structural Float'), ('STRUCTURAL_TEXT', 'Structural Text'), ('STRUCTURAL_LATEX', 'Structural Latex'), ('MCQ_EXPRESSION', 'MCQ Expression'), ('MCQ_FLOAT', 'MCQ Float'), ('MCQ_LATEX', 'MCQ Latex'), ('MCQ_TEXT', 'MCQ Text'), ('SURVEY', 'Survey')], default='STRUCTURAL_TEXT', max_length=30),
        ),
    ]
