# Generated by Django 4.2.3 on 2023-08-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0018_assignment_category_alter_question_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deduct_per_attempt',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
