# Generated by Django 4.2.3 on 2023-08-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0019_question_deduct_per_attempt_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_num_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
