# Generated by Django 4.2.3 on 2023-08-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0021_question_margin_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
                ('instances_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='hint',
            name='url',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STRUCTURAL_EXPRESSION', 'Structural Expression'), ('STRUCTURAL_FLOAT', 'Structural Float'), ('STRUCTURAL_VARIABLE_FLOAT', 'Variable Float'), ('STRUCTURAL_TEXT', 'Structural Text'), ('STRUCTURAL_LATEX', 'Structural Latex'), ('SURVEY', 'Survey'), ('MCQ_EXPRESSION', 'MCQ Expression'), ('MCQ_FLOAT', 'MCQ Float'), ('MCQ_VARIABLE_FLOAT', 'MCQ Variable Float'), ('MCQ_LATEX', 'MCQ Latex'), ('MCQ_TEXT', 'MCQ Text')], default='STRUCTURAL_TEXT', max_length=30),
        ),
        migrations.CreateModel(
            name='VariableInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.FloatField(default=-999)),
                ('upper_bound', models.FloatField(default=999)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='phobos.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='phobos.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableFloatAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_float_answers', to='phobos.question')),
            ],
        ),
        migrations.AddField(
            model_name='variable',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='phobos.question'),
        ),
        migrations.CreateModel(
            name='MCQVariableFloatAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('is_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_variable_float_answers', to='phobos.question')),
            ],
        ),
    ]
