# Generated by Django 4.2.3 on 2023-08-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0022_variable_remove_hint_url_alter_question_answer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqimageanswer',
            name='label',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STRUCTURAL_EXPRESSION', 'Structural Expression'), ('STRUCTURAL_FLOAT', 'Structural Float'), ('STRUCTURAL_VARIABLE_FLOAT', 'Variable Float'), ('STRUCTURAL_TEXT', 'Structural Text'), ('STRUCTURAL_LATEX', 'Structural Latex'), ('SURVEY', 'Survey'), ('MCQ_EXPRESSION', 'MCQ Expression'), ('MCQ_FLOAT', 'MCQ Float'), ('MCQ_VARIABLE_FLOAT', 'MCQ Variable Float'), ('MCQ_LATEX', 'MCQ Latex'), ('MCQ_TEXT', 'MCQ Text'), ('MCQ_IMAGE', 'MCQ Image')], default='STRUCTURAL_TEXT', max_length=30),
        ),
    ]
