# Generated by Django 4.2.3 on 2023-08-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0024_rename_name_questionimage_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
