# Generated by Django 4.2.3 on 2023-09-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0025_question_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
