# Generated by Django 4.2.3 on 2023-09-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0026_question_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqimageanswer',
            name='content',
            field=models.TextField(default='N/A'),
        ),
    ]
