# Generated by Django 4.2.3 on 2023-09-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0027_mcqimageanswer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionanswer',
            name='answer_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floatanswer',
            name='answer_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='latexanswer',
            name='answer_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='answer_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='is_integer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variablefloatanswer',
            name='answer_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcqimageanswer',
            name='content',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='VectorAnswer',
        ),
    ]
