# Generated by Django 4.2.3 on 2023-09-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0027_enrollmentcode'),
        ('phobos', '0028_expressionanswer_answer_unit_floatanswer_answer_unit_and_more'),
    ]

    operations = [
    ]
