# Generated by Django 4.2.3 on 2023-09-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0029_merge_20230913_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentcode',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
