# Generated by Django 4.2.4 on 2023-09-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0030_alter_enrollmentcode_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_skills', models.CharField(default='', max_length=2000)),
                ('about_course', models.CharField(default='', max_length=2000)),
                ('course_plan', models.CharField(default='', max_length=2000)),
                ('course_instructors', models.CharField(default='', max_length=2000)),
                ('instructors_image', models.ImageField(blank=True, null=True, upload_to='phobos/images/professors')),
                ('notice', models.CharField(default='', max_length=2000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_info', to='phobos.course', unique=True)),
            ],
        ),
    ]
