# Generated by Django 4.2.3 on 2023-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0030_alter_enrollmentcode_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='step_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
