# Generated by Django 4.2.4 on 2023-09-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0031_courseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_info', to='phobos.course'),
        ),
    ]
