# Generated by Django 4.2.3 on 2023-09-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0031_variable_step_size_alter_variable_symbol'),
        ('phobos', '0032_alter_courseinfo_course'),
    ]

    operations = [
    ]
