# Generated by Django 4.2.3 on 2023-09-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0034_assignment_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='step_size',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
