# Generated by Django 4.2.3 on 2023-09-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0033_merge_20230918_1546'),
        ('phobos', '0035_alter_variable_step_size'),
    ]

    operations = [
    ]
