# Generated by Django 4.2.3 on 2023-09-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0036_merge_20230922_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionanswer',
            name='preface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatanswer',
            name='preface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='latexanswer',
            name='preface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='preface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='variablefloatanswer',
            name='preface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expressionanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expression_answer', to='phobos.question'),
        ),
        migrations.AlterField(
            model_name='floatanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float_answer', to='phobos.question'),
        ),
        migrations.AlterField(
            model_name='latexanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latex_answer', to='phobos.question'),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_answer', to='phobos.question'),
        ),
        migrations.AlterField(
            model_name='variablefloatanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variable_float_answer', to='phobos.question'),
        ),
    ]
