# Generated by Django 4.2.3 on 2023-10-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0037_expressionanswer_preface_floatanswer_preface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionanswer',
            name='sufface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatanswer',
            name='sufface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='latexanswer',
            name='sufface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='sufface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='variablefloatanswer',
            name='sufface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
