# Generated by Django 4.2.3 on 2023-10-13 01:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0039_gradingscheme_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PHYSICS', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='gradingscheme',
            old_name='mcq_max_num_attempts',
            new_name='mcq_num_attempts',
        ),
        migrations.RenameField(
            model_name='gradingscheme',
            old_name='struct_max_num_attempts',
            new_name='struct_num_attempts',
        ),
        migrations.AddField(
            model_name='assignment',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='phobos.gradingscheme'),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.05, null=True),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='margin_error',
            field=models.FloatField(blank=True, default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='mcq_deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.25, null=True),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='name',
            field=models.CharField(default='Default', max_length=25),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='percentage_pts_units',
            field=models.FloatField(blank=True, default=0.1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='units_num_attempts',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='questionsettings',
            name='deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.05, null=True),
        ),
        migrations.AlterField(
            model_name='questionsettings',
            name='margin_error',
            field=models.FloatField(blank=True, default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='phobos.subject'),
            preserve_default=False,
        ),
    ]
