# Generated by Django 4.2.3 on 2023-10-13 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0040_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsettings',
            name='mcq_deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.25, null=True),
        ),
        migrations.AddField(
            model_name='questionsettings',
            name='mcq_max_num_attempts',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='questionsettings',
            name='percentage_pts_units',
            field=models.FloatField(blank=True, default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='questionsettings',
            name='units_num_attempts',
            field=models.IntegerField(default=2),
        ),
    ]
