# Generated by Django 4.2.3 on 2023-10-14 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0041_questionsettings_mcq_deduct_per_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('DIFFICULT', 'Difficult')], default='MEDIUM', max_length=10)),
                ('mcq_max_num_attempts', models.IntegerField(default=4)),
                ('mcq_deduct_per_attempt', models.FloatField(blank=True, default=0.25, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_settings', to='phobos.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StructuralQuestionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('DIFFICULT', 'Difficult')], default='MEDIUM', max_length=10)),
                ('max_num_attempts', models.IntegerField(default=5)),
                ('deduct_per_attempt', models.FloatField(blank=True, default=0.05, null=True)),
                ('margin_error', models.FloatField(blank=True, default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('percentage_pts_units', models.FloatField(blank=True, default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('units_num_attempts', models.IntegerField(default=2)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='struct_settings', to='phobos.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuestionSettings',
        ),
    ]
