# Generated by Django 4.2.3 on 2023-10-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0042_mcqquestionsettings_structuralquestionsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
