# Generated by Django 4.2.3 on 2023-10-17 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0043_question_num_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingscheme',
            name='deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='mcq_deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.25, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='mcq_num_attempts',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='num_points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='struct_num_attempts',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='units_num_attempts',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcqquestionsettings',
            name='mcq_deduct_per_attempt',
            field=models.FloatField(blank=True, default=0.25, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcqquestionsettings',
            name='mcq_max_num_attempts',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='structuralquestionsettings',
            name='max_num_attempts',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='structuralquestionsettings',
            name='units_num_attempts',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
