# Generated by Django 4.2.3 on 2023-10-28 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0044_alter_gradingscheme_deduct_per_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingscheme',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='phobos.course'),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='floor_percentage',
            field=models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='late_sub_deduct',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
