# Generated by Django 4.2.3 on 2023-10-31 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0045_gradingscheme_course_gradingscheme_floor_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STRUCTURAL_EXPRESSION', 'Structural Expression'), ('STRUCTURAL_FLOAT', 'Structural Float'), ('STRUCTURAL_VARIABLE_FLOAT', 'Variable Float'), ('STRUCTURAL_TEXT', 'Structural Text'), ('STRUCTURAL_LATEX', 'Structural Latex'), ('SURVEY', 'Survey'), ('MCQ_EXPRESSION', 'MCQ Expression'), ('MCQ_FLOAT', 'MCQ Float'), ('MCQ_VARIABLE_FLOAT', 'MCQ Variable Float'), ('MCQ_LATEX', 'MCQ Latex'), ('MCQ_TEXT', 'MCQ Text'), ('MCQ_IMAGE', 'MCQ Image'), ('MATCHING_PAIRS', 'Matching Pairs')], default='STRUCTURAL_TEXT', max_length=30),
        ),
        migrations.CreateModel(
            name='MatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_a', models.CharField(max_length=3000)),
                ('part_b', models.CharField(max_length=3000)),
                ('secret_key', models.PositiveIntegerField(default=720581478)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='phobos.question')),
            ],
        ),
    ]
