# Generated by Django 4.2.3 on 2023-10-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0046_alter_question_answer_type_matchinganswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinganswer',
            name='secret_key',
        ),
    ]
