# Generated by Django 4.2.3 on 2023-11-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0047_remove_matchinganswer_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_points',
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_info', to='phobos.course'),
        ),
    ]
