# Generated by Django 4.2.3 on 2023-12-03 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0050_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralquestionsettings',
            name='margin_error',
            field=models.FloatField(default=0.03, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
