# Generated by Django 4.2.3 on 2023-12-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobos', '0051_alter_structuralquestionsettings_margin_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableInstance2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_instances', to='phobos.question')),
            ],
        ),
    ]
