# Generated by Django 4.2.3 on 2023-12-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deimos', '0026_remove_questionstudent_var_instances2'),
        ('phobos', '0052_variableinstance2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableinstance',
            name='variable',
        ),
        migrations.AddField(
            model_name='variableinstance',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variableinstance',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var_instances', to='phobos.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variableinstance',
            name='symbol',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VariableInstance2',
        ),
    ]
